language: python
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
    - pip install tox
script:
    - tox
