language: python
python: 2.6
addons:
  apt:
    packages:
      - rpm
before_script:
  - sudo apt-get install python-rpm
  - ls /usr/lib/python*/*packages/rpm/*
  - python -c "import sys; print sys.path"
  - export PYTHONPATH=/usr/lib/python*/dist-packages:$PYTHONPATH
  - python -c 'import rpm'
env:
  - TOXENV=py26
matrix:
  include:
    - python: 2.7
      env:
      - TOXENV=py27
    - python: 3.5
      env:
      - TOXENV=py35
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
    - pip install tox
script:
    - tox
